# Generated by Django 5.0.2 on 2025-04-18 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(help_text='Rice Farm', max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('farm_size', models.DecimalField(decimal_places=2, help_text='Size in acres', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(choices=[('MAIZE', 'Maize'), ('WHEAT', 'Wheat'), ('RICE', 'Rice'), ('BEANS', 'Beans')], max_length=20)),
                ('variety', models.CharField(blank=True, max_length=100, null=True)),
                ('area_square', models.DecimalField(decimal_places=2, help_text='Area in Acres', max_digits=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='farmerDashBoard.farm')),
            ],
        ),
        migrations.CreateModel(
            name='FarmingSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('PLANTING', 'Planting'), ('GROWING', 'Growing'), ('HARVESTING', 'Harvesting'), ('COMPLETED', 'Completed')], default='PLANNING', max_length=10)),
                ('total_investment_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_yield', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='farmerDashBoard.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farming_seasons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('trend_type', models.CharField(choices=[('PRICE', 'Price'), ('DEMAND', 'Demand'), ('SUPPLY', 'Supply')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
            ],
            options={
                'unique_together': {('crop_type', 'region', 'trend_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_processed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature_high', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature_low', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precipitation', models.DecimalField(decimal_places=2, help_text='Precipitation in mm', max_digits=5)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_forecasts', to='farmerDashBoard.farm')),
            ],
            options={
                'unique_together': {('farm', 'date')},
            },
        ),
    ]
