# Generated by Django 5.0.2 on 2025-04-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplication_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
