# Generated by Django 5.0.2 on 2025-04-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loanapplication_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.DecimalField(decimal_places=3, default=0.003, help_text='Monthly interest rate (e.g., 0.003 for 0.3%)', max_digits=5),
        ),
    ]
